-- 코드를 작성해주세요
SELECT B.ID, N.FISH_NAME, B.LENGTH
FROM (    
    SELECT FISH_TYPE, ID, LENGTH
    FROM FISH_INFO
    WHERE (FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )
) B, FISH_NAME_INFO N
WHERE B.FISH_TYPE = N.FISH_TYPE
ORDER BY B.ID;