-- 코드를 입력하세요
SELECT G.TITLE, G.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD G, USED_GOODS_REPLY R
WHERE G.BOARD_ID = R.BOARD_ID
  AND G.CREATED_DATE LIKE '2022-10-%'
ORDER BY R.CREATED_DATE, G.TITLE