SELECT B.BOARD_ID, B.WRITER_ID, B.TITLE, B.PRICE, 
    CASE WHEN B.STATUS = "SALE" THEN "판매중"
         WHEN B.STATUS = "RESERVED" THEN "예약중"
         WHEN B.STATUS = "DONE" THEN "거래완료"
    END AS STATUS
FROM USED_GOODS_BOARD B
WHERE B.CREATED_DATE = "2022-10-5"
ORDER BY 1 DESC